### ISSUE TITLE
.jchart is not a function and require is not defined

### ISSUE THREAD

**Issue by pfar54** [Falkan3/jChart#1]
I added your demo base configuration code, downloaded/uploaded your src scripts and included the jquery 3.3.1 link. After doing all this, I receive the following errors.

Do you have any idea what I am doing wrong?

`jchart.js:57 Uncaught ReferenceError: require is not defined

    at jchart.js:57

    at jchart.js:19

    at jchart.js:21

(anonymous) @ jchart.js:57

(anonymous) @ jchart.js:19

(anonymous) @ jchart.js:21

jquery-3.3.1.min.js:2 jQuery.Deferred exception: $(...).jChart is not a function TypeError: $(...).jChart is not a function

    at HTMLDocument.<anonymous> (admin/index:199:32)

    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)

    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677) undefined

w.Deferred.exceptionHook @ jquery-3.3.1.min.js:2

c @ jquery-3.3.1.min.js:2

setTimeout (async)

(anonymous) @ jquery-3.3.1.min.js:2

u @ jquery-3.3.1.min.js:2

fireWith @ jquery-3.3.1.min.js:2

fire @ jquery-3.3.1.min.js:2

u @ jquery-3.3.1.min.js:2

fireWith @ jquery-3.3.1.min.js:2

ready @ jquery-3.3.1.min.js:2

_ @ jquery-3.3.1.min.js:2

jquery-3.3.1.min.js:2 Uncaught TypeError: $(...).jChart is not a function

    at HTMLDocument.<anonymous> (index:199)

    at l (jquery-3.3.1.min.js:2)

    at c (jquery-3.3.1.min.js:2)`

JS

`<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="src/js/jchart.js"></script>
<script>
$(document).ready(function() {
	//Donut Chart
	const myChart = $("#element").jChart({

	  // selectors
	  elements: {
		container: null,
		body: null,
		group: null,
		figure: null,
		svg: null,
		segments: [],
		markers: null
	  },

	  // your own data
	  data: [],

	  // values necessary for the graphing, like sum of values of all segments
	  values: {}, 

	  placeholder: {
		data: {
		  value: 0, // value of the segment
		  color: {
			normal: '#00a3f2', // stroke/fill color of the segment
			active: '#00d8f2',
		  },
		  draw: true, // whether to draw the segment on the chart or not; default true
		  push: true, // whether to push the next segment via offset. Best to set false together when draw is set to false (the empty section will always be at the end that way); default true
		  order: null, // drawing order
		  title: 'untitled',
		  strokeWidth: 3
		}
	  },

	  // appearance options
	  appearance: {
		type: 'donut', // or 'pie', 'bar'
		baseColor: '#ddd',
		segmentColor: {
			normal: '#00a3f2',
			active: '#00d8f2',
		},
		baseOffset: 0, // offset for starting point of first segment
		baseStrokeWidth: 1,
		strokeWidth: 3, // default stroke width for all segments
		animated: true,

		title: {
		  chartTitle: '',
		  showValue: true, // tooltips
		  showPercentage: true,
		  showSummary: false, // summary - show a value inside the donut chart
		  summaryTitle: '', // by default it shows the percentage of the greatest segment in the chart
		  // (if summaryTitle is empty)
		  summarySegment: null // the segment's id which percentage will be displayed in the summary
		},

		/* DONUT AND CIRCLE */
		radius: 100 / (2 * Math.PI),
		innerCutout: 0.75, // how "thin" the segments are from the center point. (0 will render a pie chart (full circle))
		centerX: 21,
		centerY: 21,

		/* DONUT */
		subType: 'circle', // render type: circle for circle based approach, path for line and arc approach using path
		isGauge: false, // if the donut will be rendered as a full circle or a half-circle
		gap: 1, // gap between segments for donut chart (in percentage, 1 = 1%)

		/* BAR */
		showMarkers: true,
		markerColor: '#f45a42',
		markerCount: 10,
		markerWidth: 0.5, // in percentage of width - 0.5 means 0.5%
		rx: 0, // horizontal corner radius
		ry: 0 // vertical corner radius
	  },

	  // callback function
	  callbacks: {
		onInit() {
		},
		onRefresh() {
		},
		onSegmentMouseover() {
		},
		onSegmentMouseout() {
		}
	  }

	});
});
</script>`

**Comment by Falkan3** [comment]
The non-jquery version is a work in progress. I have not included the jquery version in the dist folder by mistake, it is now added there.

Try loading this script in your file
`<script src="src/js/jquery.jchart.min.js"></script>`
instead of 
`<script src="src/js/jchart.js"></script>`

**Comment by pfar54** [comment]
Great that got it working! Thanks.

I can't get more than one value plotted on the donut chart, though. Here is what I have:

`// your own data
	  data: [
		{
			value: totalCatalogs
		},
		{
			value: totalProfileCat,
			color: '#b82222',
			draw: true,
			push: true
		},
		{
			value: totalFastCat,
			color: 'green',
			draw: true,
			push: true
		}
	  ],

	  // values necessary for the graphing, like sum of values of all segments
	  values: {},`

**Comment by Falkan3** [comment]
What are the values of the `totalCatalogs`, `totalProfileCat ` and `totalFastCat ` variables?

Also, the color property is an object, try passing it like in the other examples:
`color: {
    normal: '#77dd4f',
    active: '#b0ff9f'
}`

**Comment by pfar54** [comment]
Ok. Made the color change. Still only one color is showing, but now it is for only the totalFastCat value. The values are: `totalCatalogs` - 4743, `totalProfileCat` - 4736 and `totalFastCat` - 5. totalCatalogs is the entire total of them all.

**Comment by Falkan3** [comment]
Try it with these settings, works for me: 
(only 2 colors are visible as the totalFastCat's value is only 0.1% of total, so it is barely visible)

`jchart1 = $("#element1").jChart({
            data: [
                {
                    value: totalCatalogs,
                    color: {
                        normal: '#00f',
                        active: '#3b4fdb',
                    },
                    draw: true,
                    push: true
                },
                {
                    value: totalProfileCat,
                    color: {
                        normal: '#b82222',
                        active: '#d53f00'
                    },
                    draw: true,
                    push: true
                },
                {
                    value: totalFastCat,
                    color: {
                        normal: '#51e466',
						active: '#59ff70'
					},
                    draw: true,
                    push: true
                }
            ],
            appearance: {
                type: 'donut',
                subType: 'path',
                radius: 125 / (2 * Math.PI),
                gap: 0,
            }
        });`

Also you can see examples in the `test/jquery.index.html` file

**Comment by pfar54** [comment]
After adding in the values edits you made, I am still only seeing one color. Maybe it has to do with the rest of the sample code I have added?

` // values necessary for the graphing, like sum of values of all segments
	  values: {},

	  placeholder: {
		data: {
		  value: 0, // value of the segment
		  color: {
			normal: '#00a3f2', // stroke/fill color of the segment
			active: '#00d8f2',
		  },
		  draw: true, // whether to draw the segment on the chart or not; default true
		  push: true, // whether to push the next segment via offset. Best to set false together when draw is set to false (the empty section will always be at the end that way); default true
		  order: null, // drawing order
		  title: 'untitled',
		  strokeWidth: 3
		}
	  },

	  // appearance options
	  appearance: {
		type: 'donut', // or 'pie', 'bar'
		baseColor: '#ddd',
		segmentColor: {
			normal: '#00a3f2',
			active: '#00d8f2',
		},
		baseOffset: 0, // offset for starting point of first segment
		baseStrokeWidth: 1,
		strokeWidth: 3, // default stroke width for all segments
		animated: true,

		title: {
		  chartTitle: '',
		  showValue: true, // tooltips
		  showPercentage: true,
		  showSummary: false, // summary - show a value inside the donut chart
		  summaryTitle: '', // by default it shows the percentage of the greatest segment in the chart
		  // (if summaryTitle is empty)
		  summarySegment: null // the segment's id which percentage will be displayed in the summary
		},

		/* DONUT AND CIRCLE */
		radius: 100 / (2 * Math.PI),
		innerCutout: 0.75, // how "thin" the segments are from the center point. (0 will render a pie chart (full circle))
		centerX: 21,
		centerY: 21,

		/* DONUT */
		subType: 'circle', // render type: circle for circle based approach, path for line and arc approach using path
		isGauge: false, // if the donut will be rendered as a full circle or a half-circle
		gap: 1, // gap between segments for donut chart (in percentage, 1 = 1%)

		/* BAR */
		showMarkers: true,
		markerColor: '#f45a42',
		markerCount: 10,
		markerWidth: 0.5, // in percentage of width - 0.5 means 0.5%
		rx: 0, // horizontal corner radius
		ry: 0 // vertical corner radius
	  },

	  // callback function
	  callbacks: {
		onInit() {
		},
		onRefresh() {
		},
		onSegmentMouseover() {
		},
		onSegmentMouseout() {
		}
	  }`

**Comment by Falkan3** [comment]
This sample code seems to list all available options for the properties. Please refer to the examples in the `test/jquery.index.html` file.

Can I see the actual code you used while creating the jChart instance?
Like
`$(function () {
        jchart1 = $("#element1").jChart({
            data: [
                {
                    value: totalCatalogs,
                    color: {
                        normal: '#00f',
                        active: '#3b4fdb',
                    }
                },
                {
                    value: totalProfileCat,
                    color: {
                        normal: '#b82222',
                        active: '#d53f00'
                    }
                },
                {
                    value: totalFastCat,
                    color: {
                        normal: '#51e466',
						active: '#59ff70'
					}
                }
            ],
            appearance: {
                type: 'donut',
                subType: 'path',
                radius: 125 / (2 * Math.PI),
                gap: 0,
            }
        });
});`

**Comment by pfar54** [comment]
`//Donut Chart
	const myChart = $("#element").jChart({

	  // selectors
	  elements: {
		container: null,
		body: null,
		group: null,
		figure: null,
		svg: null,
		segments: [],
		markers: null
	  },

	  // your own data
	data: [
		{
			value: totalCatalogs,
			color: { normal: '#00f', active: '#3b4fdb', },
			draw: true,
			push: true
		},
		{
			value: totalProfileCat,
			color: { normal: '#b82222', active: '#d53f00' },
			draw: true,
			push: true
		},
		{
			value: totalFastCat,
			color: { normal: '#51e466', active: '#59ff70' },
			draw: true,
			push: true
		}
	],

	  // values necessary for the graphing, like sum of values of all segments
	  values: {},

	  placeholder: {
		data: {
		  value: 0, // value of the segment
		  color: {
			normal: '#00a3f2', // stroke/fill color of the segment
			active: '#00d8f2',
		  },
		  draw: true, // whether to draw the segment on the chart or not; default true
		  push: true, // whether to push the next segment via offset. Best to set false together when draw is set to false (the empty section will always be at the end that way); default true
		  order: null, // drawing order
		  title: 'untitled',
		  strokeWidth: 3
		}
	  },

	  // appearance options
	  appearance: {
		type: 'donut', // or 'pie', 'bar'
		baseColor: '#ddd',
		segmentColor: {
			normal: '#00a3f2',
			active: '#00d8f2',
		},
		baseOffset: 0, // offset for starting point of first segment
		baseStrokeWidth: 1,
		strokeWidth: 3, // default stroke width for all segments
		animated: true,

		title: {
		  chartTitle: '',
		  showValue: true, // tooltips
		  showPercentage: true,
		  showSummary: false, // summary - show a value inside the donut chart
		  summaryTitle: '', // by default it shows the percentage of the greatest segment in the chart
		  // (if summaryTitle is empty)
		  summarySegment: null // the segment's id which percentage will be displayed in the summary
		},

		/* DONUT AND CIRCLE */
		radius: 100 / (2 * Math.PI),
		innerCutout: 0.75, // how "thin" the segments are from the center point. (0 will render a pie chart (full circle))
		centerX: 21,
		centerY: 21,

		/* DONUT */
		subType: 'circle', // render type: circle for circle based approach, path for line and arc approach using path
		isGauge: false, // if the donut will be rendered as a full circle or a half-circle
		gap: 1, // gap between segments for donut chart (in percentage, 1 = 1%)

		/* BAR */
		showMarkers: true,
		markerColor: '#f45a42',
		markerCount: 10,
		markerWidth: 0.5, // in percentage of width - 0.5 means 0.5%
		rx: 0, // horizontal corner radius
		ry: 0 // vertical corner radius
	  },

	  // callback function
	  callbacks: {
		onInit() {
		},
		onRefresh() {
		},
		onSegmentMouseover() {
		},
		onSegmentMouseout() {
		}
	  }

	});`

**Comment by Falkan3** [comment]
It works for me
![image](https://user-images.githubusercontent.com/15730072/61066686-4b347980-a406-11e9-82ca-1d737d9febde.png)

You'd have to send the whole project file (html) if you're still having issues. Do the example charts show properly for you?

Also, all this code isn't needed, it only shows all the possible properties you can pass while creating a chart.

**Comment by pfar54** [comment]
Here is my full file.

`<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);
include($_SERVER['DOCUMENT_ROOT'].'/core/init.php');

if(Session::exists('home')) {
	//echo '<p>' . Session::flash('home') . '</p>';
}
if(!$user->isLoggedIn()) {
	Redirect::to('login');
}

//Fix Dates
//require_once("fixDate.php");

//Profile pic in main
/*$sql_profile_img = "
  SELECT *
  FROM profile_img
  WHERE user_id = ?
  ORDER BY id DESC LIMIT 1
  ";
	if ($stmt_profile_img = $con->prepare($sql_profile_img)) {
		$stmt_profile_img->execute(array($user_id));
		
		$default_profile_img = NULL;
		$userProfilePic = NULL;
		$profilePic = NULL;
		$profile_rows = $stmt_profile_img->fetchAll(PDO::FETCH_ASSOC);
		foreach ($profile_rows as $profile_row) {
			$profilePic = $profile_row['img'];
		}
		if ($profilePic == NULL) {
			$default_profile_img = '<img class="home-profile-pic" src="profile_images/default.jpg">';
		} else {
			$userProfilePic =  '<img class="home-profile-pic" src=" '.$profilePic.'">';
		}
	}
	*/
//include_once("required_files/page-count");	
//Page count
//require_once ("required_files/page-count");
//require_once 'required_files/page-count.php';

?>
<!DOCTYPE html>





 <html lang="en" class="no-js"> 
<head>
	<title>Admin Dashboard</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1.0">

	<meta property="og:title" content="">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
	<meta property="og:description" content="">
	<meta name="robots" content="noindex, nofollow">
	
	<link type="text/css" rel="stylesheet" href="../styles/main-style.css">
	<link href="https://fonts.googleapis.com/css?family=Nunito:400,600,800|Muli:300,400,800" rel="stylesheet">
	<link rel="alternate" href="" hreflang="en-us">
	<link rel="icon" type="image/png" sizes="16x16" href="/icons/favicons/favicon-16x16.png">
<style>

/* -- Dash Grid -- */

/* -- Donut Chart -- */
.jchart--donut--segment, .jchartpie--segment {
  transition: stroke-dasharray 1s ease;
}

.jchart {
  width: 400px;
  height: 400px;
}

.jchart--body {
  width: 100%;
  height: 100%;
}

#dashGrid {
	margin: 60px 0;
}
.dashGridBox, .dashGridBoxMain {
	width: 25%;
	display: inline-block;
	vertical-align: top;
	padding: 10px 0;
	margin: 15px 0;
	text-align: center;
	border-right: 1px solid #CCC;
}
.dashGridBoxMain {
	width: 50%;
}
.dashGridTitle {
	color: #2d2d2d;
	font-family: "Muli", sans-serif;
	font-size: 1.4rem;
	margin-bottom: 20px;
}
.subViewBox {
	width: 100%;
	height: auto;
	border-bottom: 1px solid #b82222;
	text-align: left;
	padding: 10px 0;
	margin: 20px 0;
}
.subViewBoxTitle {
	color: #2d2d2d;
	font-family: "Muli", sans-serif;
	font-size: 1rem;
}
/* -- Sub View Box -- */
.subViewBoxExpand {
	display: none;
}
.subViewBoxExpand.active {
	display: block;
}
/*----------------------------------------------PHONE MEDIA QUERY 640--------------------------------------------*/

@media screen and (max-width:640px) {
	


}
</style>
</head>
<body>
<?php
include_once($_SERVER['DOCUMENT_ROOT'].'/analyticstracking.php');
echo $setup_popup;

$permission = $user->getGroup();

echo $permission;
if($permission == 'User') {
	include($_SERVER['DOCUMENT_ROOT'].'/admin/Nav/userNav.php');
} else if ($permission == 'Admin') {
	include($_SERVER['DOCUMENT_ROOT'].'/admin/Nav/adminNav.php');
}

//include_once("nav/friend-bar.php");

if($user->hasPermission('Admin')) {
	echo '<p>Admin!<p>';
}
?>
<section id="dashGrid">
	<div class="dashGridBoxMain">
		<span class="dashGridTitle">Total Catalog Views</span>
		<div id="totalCatalogViews"></div>
			<div id="element"></div>
	</div>
	<div class="dashGridBox">
		<span class="dashGridTitle">Catalog Type Views</span>
		<div id="subView">
			<div class="subViewBox">
				<span class="subViewBoxTitle">Profile Catalogs</span><span class="arrow"> ></span>
				<div id="totalProfileViews"></div>
				<div class="subViewBoxExpand">
					<p>Total Popular Views: <span id="totalProfilePopViews"></span></p>
					<p>Total Product Specific Views: <span id="totalProfileProdViews"></span></p>
				</div>
			</div>
			<div class="subViewBox">
				<span class="subViewBoxTitle">Fast Tech Catalogs</span><span class="arrow"> ></span>
				<div id="totalFastViews"></div>
				<div class="subViewBoxExpand">
					<p>Total Popular Views: <span id="totalFastTechPopViews"></span></p>
					<p>Total Product Specific Views: <span id="totalFastTechProdViews"></span></p>
				</div>
			</div>
			<div id="totalProfilePopViews"></div>
			<div id="totalProfileSpecificViews"></div>
			<div id="totalFastTechPopViews"></div>
		</div>
	</div>
</section>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script>
$(document).ready(function() {

	$('.arrow').click(function() {
		var i = $(this).closest('.subViewBox').find('.subViewBoxExpand'),
            t = $(this).addClass('active');
			i.slideToggle(500).find('.subViewBoxExpand').animate({
            opacity: 1
        }, 1500) + t, $('.subViewBoxExpand').not(i).slideUp(800).prev().removeClass('active');
		//$('.subViewBoxExpand').toggleClass('active');
	});

	//Totals
	var totalCatalogs = ''; //Total Catalogs
	var totalProfileCat = ''; //Total Profile Catalogs
	var totalFastCat = ''; //Total Fastening Tech Catalogs
	//Total Popular
	var totalProfilePop = '';
	var totalFastPop = '';
	//Total Product Specific
	var totalProfileSpec = '';
	var totalFastSpec = '';

	function ajaxCallCatalogs() {
		$.ajax({
			url: 'php/catalogSelect.php',
			datatype: 'json',
			success: function (data) {
				//console.log(data);
				obj = JSON.parse(data);

				totalCatalogs = obj.totalCount; //Total Catalogs
				totalProfileCat = obj.totalProfile; //Total Profile Catalogs
				totalFastCat = obj.totalFastTech; //Total Fastening Tech Catalogs
				//Total Popular
				totalProfilePop = obj.totalProfilePopular;
				totalFastPop = obj.totalFastTechPopular;
				//Total Product Specific
				totalProfileSpec = obj.totalProfileProdSpec;
				totalFastSpec = obj.totalFastTechProdSpec;

				$('#totalCatalogViews').html(totalCatalogs);
				$('#totalProfileViews').html(totalProfileCat);
				$('#totalProfilePopViews').html(totalProfilePop);
				$('#totalProfileProdViews').html(totalProfileSpec);
				$('#totalFastViews').html(totalFastCat);
				$('#totalFastTechPopViews').html(totalFastPop);
				$('#totalFastTechProdViews').html(totalFastSpec);
			}
		});
	}
	ajaxCallCatalogs();
	setInterval(ajaxCallCatalogs, 150000); //1 min call 60000

	//Donut Chart
	const myChart = $("#element").jChart({

	  // selectors
	  elements: {
		container: null,
		body: null,
		group: null,
		figure: null,
		svg: null,
		segments: [],
		markers: null
	  },

	  // your own data
	data: [
		{
			value: totalCatalogs,
			color: { normal: '#00f', active: '#3b4fdb', },
			draw: true,
			push: true
		},
		{
			value: totalProfileCat,
			color: { normal: '#b82222', active: '#d53f00' },
			draw: true,
			push: true
		},
		{
			value: totalFastCat,
			color: { normal: '#51e466', active: '#59ff70' },
			draw: true,
			push: true
		}
	],

	  // values necessary for the graphing, like sum of values of all segments
	  values: {},

	  placeholder: {
		data: {
		  value: 0, // value of the segment
		  color: {
			normal: '#00a3f2', // stroke/fill color of the segment
			active: '#00d8f2',
		  },
		  draw: true, // whether to draw the segment on the chart or not; default true
		  push: true, // whether to push the next segment via offset. Best to set false together when draw is set to false (the empty section will always be at the end that way); default true
		  order: null, // drawing order
		  title: 'untitled',
		  strokeWidth: 3
		}
	  },

	  // appearance options
	  appearance: {
		type: 'donut', // or 'pie', 'bar'
		baseColor: '#ddd',
		segmentColor: {
			normal: '#00a3f2',
			active: '#00d8f2',
		},
		baseOffset: 0, // offset for starting point of first segment
		baseStrokeWidth: 1,
		strokeWidth: 3, // default stroke width for all segments
		animated: true,

		title: {
		  chartTitle: '',
		  showValue: true, // tooltips
		  showPercentage: true,
		  showSummary: false, // summary - show a value inside the donut chart
		  summaryTitle: '', // by default it shows the percentage of the greatest segment in the chart
		  // (if summaryTitle is empty)
		  summarySegment: null // the segment's id which percentage will be displayed in the summary
		},

		/* DONUT AND CIRCLE */

		radius: 100 / (2 * Math.PI),
		innerCutout: 0.75, // how "thin" the segments are from the center point. (0 will render a pie chart (full circle))
		centerX: 21,
		centerY: 21,

		/* DONUT */
		subType: 'circle', // render type: circle for circle based approach, path for line and arc approach using path
		isGauge: false, // if the donut will be rendered as a full circle or a half-circle
		gap: 1, // gap between segments for donut chart (in percentage, 1 = 1%)

		/* BAR */
		showMarkers: true,
		markerColor: '#f45a42',
		markerCount: 10,
		markerWidth: 0.5, // in percentage of width - 0.5 means 0.5%
		rx: 0, // horizontal corner radius
		ry: 0 // vertical corner radius
	  },

	  // callback function
	  callbacks: {
		onInit() {
		},
		onRefresh() {
		},
		onSegmentMouseover() {
		},
		onSegmentMouseout() {
		}
	  }

	});
});
</script>
</body>
</html>`

**Comment by Falkan3** [comment]
Tried it with your settings and it works for me. Try to create a new empty html file and make a chart there, see how it goes. Or use the example file.
[jChart.zip](https://github.com/Falkan3/jChart/files/3383033/jChart.zip)
Download it, extract and run the `test/jquery.index.html` file.

**Comment by pfar54** [comment]
I get the same thing with the test file. You can see it here: https://mbkit.com/admin/test/jquery.index.html

**Comment by Falkan3** [comment]
OK I think I know the issue: change the subType from 'circle' to 'path'. The Circle subtype is bugged for tiny values.
`appearance: {
                type: 'donut',
                subType: 'path'
            },`
You can also set 'gap' to 0.

There are some leftover bugs when a segment's value is less than 1%. I never got to fixing it, but it works when the subType is set to 'path' and the gap is 0

**Comment by pfar54** [comment]
I got it to work on the test, but on my normal file it is doing the same. The only thing I can think of is that mine is wrapped in a doc ready. Would that have any impact?

**Comment by Falkan3** [comment]
It shouldn't have any impact. Maybe you are viewing an older cached version?

**Comment by pfar54** [comment]
I have tried in different browsers. I see my jquery type is different, too. Would that make a difference? I am using: https://code.jquery.com/jquery-3.3.1.min.js

**Comment by Falkan3** [comment]
It shouldn't make a difference, but it's worth a shot if everything is the same as in the version you got to work. Try removing all the unneccessary code in jchart settings.

**Comment by pfar54** [comment]
I tried the jquery version, the src file you were using (I was using the min file), and removing some of the other code - nothing.

**Comment by Falkan3** [comment]
The subType property is declared twice. Remove the second occurence and you should be good to go.
![image](https://user-images.githubusercontent.com/15730072/61075620-aa03ee00-a41a-11e9-8f63-dd012fbe0423.png)

**Comment by pfar54** [comment]
I tried that a bit earlier. It grays out the circle and leaves a whole bunch of errors. Just did it on the production so you could see.

**Comment by Falkan3** [comment]
It does work, but the values you give to segments are empty strings "", which causes errors. Try to debug the script you wrote.
When I set values to the variables it works:
![image](https://user-images.githubusercontent.com/15730072/61076157-de2bde80-a41b-11e9-9fda-a09bf2897046.png)

**Comment by pfar54** [comment]
Are you referring to this `// values necessary for the graphing, like sum of values of all segments
        values: {},` or within the data array?

**Comment by Falkan3** [comment]
The variables you pass for segments in `data: {}`. If you debug, you can see when the jchart is created the values of the variables are empty strings.

**Comment by pfar54** [comment]
Ahh gotcha. I thought if you delcare a variable outside of a function it makes it global. Then in the function it changes the value. Is there something I need to do to make these variables global?

**Comment by Falkan3** [comment]
The variables are accessible inside the chart initialization function, just the values you've given them as defaults are string. Try changing them to 0.
`//Totals
	var totalCatalogs = ''; //Total Catalogs
	var totalProfileCat = ''; //Total Profile Catalogs
	var totalFastCat = ''; //Total Fastening Tech Catalogs
	//Total Popular
	var totalProfilePop = '';
	var totalFastPop = '';
	//Total Product Specific
	var totalProfileSpec = '';
	var totalFastSpec = '';`

I see you are using ajax to get the data, which is called after the charts are initialized erroneously with strings as values instead of numbers. Simply change the above values to 0's, or create the charts on the success callback of the ajax call.

To update the data after it changes you can use the jchart update function.
`
jchart1.settings.data = [
   {...}
];
jchart1._methods.Update(jchart1);
`

**Comment by pfar54** [comment]
ok, I changed the variables to 0. No difference.

My ajax function is called before the jchart function.

How would I add in the function? `jchart1.settings.data = [ {...} ]; jchart1._methods.Update(jchart1);`

**Comment by Falkan3** [comment]
It is called before, but it is asynchronous, which means it will finish after the next lines are called.
As you can see there are no errors anymore, but the chart is empty because the values are 0.
Just add this inside the ajax success callback function. This will refresh the values with the new ones from the ajax call.
`myChart.settings.data = [
		{
			value: totalCatalogs,
			color: { normal: '#00f', active: '#3b4fdb', }
		},
		{
			value: totalProfileCat,
			color: { normal: '#b82222', active: '#d53f00' }
		},
		{
			value: totalFastCat,
			color: { normal: '#51e466', active: '#59ff70' }
		}
	];
myChart._methods.Update(myChart);`

**Comment by pfar54** [comment]
Gotcha. This error is showing after doing so. `jquery.jchart.js:828 Uncaught TypeError: Cannot read property '0' of undefined
    at Object.drawBodySegmentDonut (jquery.jchart.js:828)
    at Plugin.<anonymous> (jquery.jchart.js:1300)
    at tick (jquery.jchart.js:1262)`

**Comment by Falkan3** [comment]
The value you pass is a string, try to make it a number. You can use `parseInt(your_variable_name);` function.

**Comment by pfar54** [comment]
I tried this, but it didn't help. `{
			value: parseInt(totalCatalogs),
			color: { normal: '#00f', active: '#3b4fdb', },
			draw: true,
			push: true
		},`

**Comment by Falkan3** [comment]
Do it on this line, when settings the values to segments:
`myChart.settings.data = [ { value: totalCatalogs, color: { normal: '#00f', active: '#3b4fdb', } }, { value: totalProfileCat, color: { normal: '#b82222', active: '#d53f00' } }, { value: totalFastCat, color: { normal: '#51e466', active: '#59ff70' } } ];`

**Comment by pfar54** [comment]
Just tried that. It didn't help unfortunately.

**Comment by Falkan3** [comment]
OK I think I know what's causing the issue, setting the data overrides other variables. Try to only change the value in the data object:

`myChart.settings.data[0].value = parseInt(totalCatalogs);  
myChart.settings.data[1].value = parseInt(totalProfileCat);  
myChart.settings.data[2].value = parseInt(totalFastCat);`

You can also use the Refresh method instead of Update if you want the chart to draw from scratch.
`myChart._methods.Refresh(myChart);`

**Comment by pfar54** [comment]
Thanks! This did the trick. I still don't understand why my variables aren't global. Is there an alternative way to make them global before getting to the jchart code?

**Comment by Falkan3** [comment]
To make them global you can set them directly on the window object like so:
`window.your_variable = 100;`
or you can define them out of function scopes, which means outside of the document ready function:
`<script>global_variable = 100;</script>`
(which will automatically declare the variable on the window object anyway)

**Comment by pfar54** [comment]
So If I did `var totalCatalogs = 0;` and then in my ajax call the variable is updated, will this value be updated and work in jchart without needing to do the jchart refresh?

**Comment by Falkan3** [comment]
Not really, as the jchart instance stores the copy of that value locally. That would need setting up observers to check for any changes made to the variable. It is possible to do, many reactive frameworks work that way. But it is not implemented here. You could of course write your own setter function that would do that for you, so instead of changing the value by hand you would call the function that sets the value and calls the update function:

`
function setValue(value) {
    window.your_value = value;
    window.myChart.settings.data[0].value = value;
    window.myChart._methods.Update(window.myChart);
}
`

Alternatively, if you pass a reference to an object instead of a value it will reflect changes everywhere, but you would still need to call the Update function anyway.

`
var test = {
	var: 5
};
var test2 = test;
test2.var = 6;
`
test.var now equals 6 as well.

I must say, this is an older project that I made for practice. If you need a good charting library, check out [chart.js](https://www.chartjs.org/). It has many more options, allows multiple datasets, and has built-in tooltips.

**Comment by pfar54** [comment]
You are wonderful at helping! I will check out the other option, though I think you did a fine job creating your version. I'm simply using it for myself for measuring metrics at work, so it has been a nice fun learning experience.

Can you expand on this though: 'Alternatively, if you pass a reference to an object instead of a value it will reflect changes everywhere, but you would still need to call the Update function anyway.'

**Comment by Falkan3** [comment]
When you assign an object to a variable, it becomes a reference, meaning there are no multiple copies of it, just a pointer to the object. That means, when you have multiple variables referencing an object, they will all change when you set a new value to a parameter of the said object. But I don't think it will work here, I'd have to modify the code for it to work this way. In the plugin I just copy the values passed in the `options` variable.
